# Daily Portfolio YTD Return Calculation Workflow
name: Daily Portfolio YTD Calculation

# Run daily at 9:00 AM UTC (adjust timezone as needed)
on:
  schedule:
    - cron: '0 9 * * *'
  
  # Allow manual triggering of the workflow
  workflow_dispatch:

# Grant write permissions to the workflow
permissions:
  contents: write

jobs:
  calculate-portfolio-ytd:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v4
    
    # Set up Python environment
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    # Cache pip dependencies for faster runs
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    # Install Python dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        else
          # Install the required packages based on your script
          pip install requests
        fi
    
    # Verify required files exist
    - name: Check required files
      run: |
        if [ ! -f "fetch_ytd.py" ]; then
          echo "Error: fetch_ytd.py not found"
          exit 1
        fi
        if [ ! -f "portfolio_config.json" ]; then
          echo "Error: portfolio_config.json not found"
          exit 1
        fi
    
    # Run the portfolio YTD calculation script
    - name: Run Portfolio YTD Calculation
      run: |
        python fetch_ytd.py
    
    # Commit and push results if files were updated
    - name: Commit and push results
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Add any generated or updated files
        if [ -f "portfolio_ytd_results.json" ]; then
          git add portfolio_ytd_results.json
        fi
        
        # Check for yearly archive files (if it's December 31st)
        if ls portfolio_ytd_results_*.json 1> /dev/null 2>&1; then
          git add portfolio_ytd_results_*.json
        fi
        
        # Commit if there are changes
        if ! git diff --staged --quiet; then
          git commit -m "Update portfolio YTD results - $(date +'%Y-%m-%d %H:%M:%S')"
          git push
        else
          echo "No changes to commit"
        fi
    
    # Upload results as artifacts (optional - for debugging)
    - name: Upload results as artifact
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: portfolio-results-${{ github.run_number }}
        path: |
          portfolio_ytd_results.json
          portfolio_ytd_results_*.json
        retention-days: 30
