name: Update PnL History Daily

on:
  schedule:
    - cron: '0 1 * * *'  # 1am CET
  workflow_dispatch:

jobs:
  update-pnl-history:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}
          fetch-depth: 0
          path: 'portfolio'  # Explicitly check out to this directory

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pytz

      - name: Run PnL history generator
        run: |
          cd portfolio
          python generate_pnl_history.py

      - name: Commit and push changes
        if: success()
        run: |
          cd portfolio
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add pnl_history.json
          git status
          git diff --cached --quiet || (git commit -m "Update PnL history [skip ci]" && git push origin HEAD) 