name: Scrape Exchange Rate

on:
  schedule:
    - cron: '0,30 * * * *'  # This will run the script at minute 0 and minute 30 of every hour
  workflow_dispatch:  # This allows you to manually trigger the workflow from GitHub Actions UI

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run the scraping script
      run: python scrape_exchange_rate.py

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        branch: main
        force: true
