name: Update Portfolio History

on:
  schedule:
    - cron: '0 1 * * *'  # Runs at 1am CET every day
  workflow_dispatch:  # Allow manual triggers

jobs:
  update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout current repo
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        # Install Chrome
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        # Install ChromeDriver (matching Chrome version)
        CHROME_VERSION=$(google-chrome --version | cut -d ' ' -f 3)
        CHROME_MAJOR_VERSION=${CHROME_VERSION%.*.*}
        wget -q https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_MAJOR_VERSION}
        CHROMEDRIVER_VERSION=$(cat LATEST_RELEASE_${CHROME_MAJOR_VERSION})
        wget -q https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pytz
        
    - name: Run portfolio updater
      run: python portfolio_updater.py
    
    - name: Commit and push changes
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        script: |
          const { execSync } = require('child_process');
          execSync('git config --global user.name "GitHub Actions"');
          execSync('git config --global user.email "actions@github.com"');
          execSync('git add portfolio_history.json');
          const status = execSync('git status --porcelain').toString();
          if (status) {
            execSync('git commit -m "Update portfolio history [skip ci]"');
            execSync('git push');
          }
